/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface LMap {
    'iconUrl': string;
    'locations': string;
    'tileLayer': string;
  }
  interface LMapAttributes extends StencilHTMLAttributes {
    'iconUrl'?: string;
    'locations'?: string;
    'tileLayer'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'LMap': Components.LMap;
  }

  interface StencilIntrinsicElements {
    'l-map': Components.LMapAttributes;
  }


  interface HTMLLMapElement extends Components.LMap, HTMLStencilElement {}
  var HTMLLMapElement: {
    prototype: HTMLLMapElement;
    new (): HTMLLMapElement;
  };

  interface HTMLElementTagNameMap {
    'l-map': HTMLLMapElement
  }

  interface ElementTagNameMap {
    'l-map': HTMLLMapElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
